# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: Install depedencies
          command: npm i
      - run:
          name: Run build
          command: npm run build
      - add_ssh_keys:
          fingerprints:
            - "03:20:40:a7:1d:61:0c:45:d0:d7:ed:d6:f6:40:df:5c"
      - run:
          name: Deploy to EC2
          command: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "03:20:40:a7:1d:61:0c:45:d0:d7:ed:d6:f6:40:df:5c" -r public_html ubuntu@ec2-3-120-129-169.eu-central-1.compute.amazonaws.com:/var/www/firechat
